<?php
/**
 * Block layout view.
 *
 * Copyright ©2022 Kaeness
 * Author: Christian Lescuyer / Goélette

 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $block_heading
 *
 * @see https://docs.laminas.dev/laminas-view/helpers/escape/
 */
declare(strict_types=1);

$assetUrl = $this->plugin('assetUrl');

$this->headLink()->appendStylesheet($assetUrl('css/share-me-baby.css', 'ShareMeBaby'));
?>

<div class="share-me-baby">
    <h3 class="share-me-baby__heading"><?= $block_heading ?></h3>
    <div class="share-me-baby__buttons">

<?php
if ( in_array('enable_facebook', $networks ) ) {
    $url = 'https://www.facebook.com/sharer/sharer.php?u=' . $this->escapeUrl($this_url);
?>

        <a class="button facebook" target="_blank" href="<?= $url ?>" rel="noopener noreferrer nofollow">
            <svg viewbox="0 0 512 512" class="share-me-baby__icon facebook" fill="currentcolor" height="1em" width="1em" aria-hidden="true" focusable="false" role="img">
                <path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"></path>
            </svg>
            <span class="share-me-baby__name">
                <span class="screen-reader-text"><?php echo $this->translate('Share on'); ?></span>
                Facebook
            </span>
        </a>

<?php
}
if ( in_array('enable_twitter', $networks ) ) {

    $url  = 'https://twitter.com/intent/tweet';
    $url .= '?text=' . $this->escapeUrl($title);
    $url .= '&amp;url=' . $this->escapeUrl($this_url);
    if ('' != $twitter_handle) {
        $url .= '&amp;related=' . $this->escapeUrl($twitter_handle);
        $url .= '&amp;via=' . $this->escapeUrl($twitter_handle);
    }
?>

        <a class="button twitter" target="_blank" href="<?= $url ?>" rel="noopener noreferrer nofollow">
            <svg viewbox="0 0 512 512" class="share-me-baby__icon twitter" fill="currentcolor" height="1em" width="1em" aria-hidden="true" focusable="false" role="img">
                <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/>
            </svg>
            <span class="share-me-baby__name">
                <span class="screen-reader-text"><?php echo $this->translate('Share on'); ?></span>
                X (Twitter)
            </span>
        </a>

<?php
}
if ( in_array('enable_linkedin', $networks ) ) {

    $params = array(
        'mini'   => '1',
        'url'    => $this_url,
        'title'  => $title,
        'source' => $this->serverUrl(),
    );
    $url = 'https://www.linkedin.com/shareArticle?' . http_build_query($params, '', '&amp;');
?>

        <a class="button linkedin" target="_blank" href="<?= $url ?>" rel="noopener noreferrer nofollow">
            <svg viewbox="0 0 448 512" class="share-me-baby__icon linkedin" fill="currentcolor" height="1em" width="1em" aria-hidden="true" focusable="false" role="img">
                <!-- Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) -->
                <path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path>
            </svg>
            <span class="share-me-baby__name">
                <span class="screen-reader-text"><?php echo $this->translate('Share on'); ?></span>
                LinkedIn
            </span>
        </a>

<?php
}
if ( in_array('enable_email', $networks ) ) {

    $body    = $this->translate('Check this link: ') . $this->escapeUrl($this_url);         // @todo Message en option
    $subject = $this->translate('Sharing this page: ') . $this->escapeHtml($title);  // @todo Titre en option
    $url     = 'mailto:?subject=' . $subject . '&amp;body=' . $body;
?>
        <a class="button email" href="<?= $url ?>" rel="noopener noreferrer nofollow">
            <svg viewbox="0 0 512 512" class="share-me-baby__icon email" fill="currentcolor" height="1em" width="1em" aria-hidden="true" focusable="false" role="img">
                <!-- Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) -->
                <path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path>
            </svg>
            <span class="share-me-baby__name">
                <span class="screen-reader-text"><?php echo $this->translate('Share on'); ?></span>
                Email
            </span>
        </a>

<?php
}
?>

    </div>
</div>
